FROM quintenk/jdk7-oracle

MAINTAINER Pini Reznik <p.reznik@uglyduckling.nl>

RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
RUN apt-get update

RUN apt-get install -y maven
